name: fluttertoast
description: Toast Library for Flutter, Easily create toast messages in single line of code
version: 4.0.1
homepage: https://github.com/PonnamKarthik/FlutterToast

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.ponnamkarthik.toast.fluttertoast
        pluginClass: FluttertoastPlugin
      ios:
        pluginClass: FluttertoastPlugin
      web:
        pluginClass: FluttertoastWebPlugin
        fileName: fluttertoast_web.dart